services:
  - type: web
    name: chatai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m gunicorn app:app --bind 0.0.0.0:$PORT --workers 4 --timeout 120 --preload
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: WEB_CONCURRENCY
        value: 4
      - key: SECRET_KEY
        generateValue: true
    autoDeploy: true
